const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const http = require("node:http");
const { app, BrowserWindow, session } = require("electron");
const { installPermissionPolicy, studioCsp } = require("../studio-policy.cjs");
app.disableHardwareAcceleration();
app.commandLine.appendSwitch("disable-dev-shm-usage");
app.commandLine.appendSwitch("no-sandbox");
app.commandLine.appendSwitch("use-fake-device-for-media-stream");
let root;
let server;
const timeout = setTimeout(() => finish(new Error("Studio policy browser test timed out")), 25000);
async function finish(error) {
  clearTimeout(timeout);
  for (const window of BrowserWindow.getAllWindows()) window.destroy();
  if (server) server.close();
  if (root) fs.rmSync(root, { recursive: true, force: true });
  if (error) console.error(error);
  else console.log("Studio CSP, worker, local-report and real audio permission checks passed.");
  app.exit(error ? 1 : 0);
}
app.whenReady().then(async () => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), "taskurotta-policy-"));
  server = http.createServer((_req, res) => { res.setHeader("Content-Type", "text/html"); res.end("<!doctype html><title>Remote</title>"); });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const apiBaseUrl = `http://127.0.0.1:${server.address().port}`;
  const indexPath = path.join(root, "index.html");
  const options = { indexPath, devServerUrl: "http://127.0.0.1:5173", isProduction: true, apiBaseUrl };
  fs.writeFileSync(indexPath, `<!doctype html><meta http-equiv="Content-Security-Policy" content="${studioCsp(options)}"><script>window.inlineExecuted=true</script><script src="./allowed.js"></script><body></body>`);
  fs.writeFileSync(path.join(root, "allowed.js"), 'window.allowedScript=true; window.workerResult=new Promise((resolve,reject)=>{const worker=new Worker("./worker.js");worker.onmessage=e=>{resolve(e.data);worker.terminate()};worker.onerror=reject});');
  fs.writeFileSync(path.join(root, "worker.js"), 'self.postMessage("worker-ok")');
  const studio = new BrowserWindow({ show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, webviewTag: true } });
  const remoteSession = session.fromPartition("policy-remote-test");
  installPermissionPolicy(remoteSession, studio.webContents.session, () => studio.webContents, options);
  await studio.loadFile(indexPath);
  const result = await studio.webContents.executeJavaScript('(async()=>({script:window.allowedScript,inline:window.inlineExecuted||false,worker:await window.workerResult,audio:await navigator.mediaDevices.getUserMedia({audio:true}).then(s=>{s.getTracks().forEach(t=>t.stop());return true})}))()');
  assert.deepEqual(result, { script: true, inline: false, worker: "worker-ok", audio: true });
  assert.equal(await studio.webContents.executeJavaScript(`new Promise((resolve,reject)=>{const guest=document.createElement("webview");guest.partition="policy-remote-test";guest.src=${JSON.stringify(apiBaseUrl)};guest.addEventListener("did-finish-load",()=>{resolve(true);guest.remove()});guest.addEventListener("did-fail-load",e=>reject(new Error(e.errorDescription)));document.body.append(guest)})`), true);
  const remote = new BrowserWindow({ show: false, webPreferences: { partition: "policy-remote-test", sandbox: true, contextIsolation: true, nodeIntegration: false } });
  await remote.loadURL(apiBaseUrl);
  assert.equal(await remote.webContents.executeJavaScript('navigator.mediaDevices.getUserMedia({audio:true}).then(s=>{s.getTracks().forEach(t=>t.stop());return "allowed"},e=>e.name)'), "NotAllowedError");
  const report = path.join(root, "report.html");
  fs.writeFileSync(report, '<!doctype html><style>body{color:rgb(23,54,31)}</style><script>window.reportLoaded=true</script><body>Local report</body>');
  await remote.loadFile(report);
  assert.equal(await remote.webContents.executeJavaScript('window.reportLoaded'), true);
  await finish();
}).catch(finish);
